# Site settings
title: Xamarin.Forms Complete
header-img: img/xamarin-forms.jpg
email: jason@xamarin.com
description: "A simple blog about Xamarin tips and tricks."
baseurl: ""
url: "http://jassmith.github.io"
twitter_username: jassmith87
github_username:  jassmith

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]

analytics :
  provider : google
  google : 
      tracking_id : 'UA-72408475-1'